### ISSUE TITLE
Consider bumping minimum supported `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [thejameskyle/object-assign-sorted#1]
So you can just use the native `Object.assign` instead of `object-assign`.

**Comment by thejameskyle** [comment]
Done. See 2.0.0

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for your time.

**Comment by hzoo** [comment]
Oh we didn't modify the src @thejameskyle https://github.com/thejameskyle/object-assign-sorted/blob/master/index.js#L1 to use native `Object.assign`

**Comment by hzoo** [comment]
Made https://github.com/thejameskyle/object-assign-sorted/pull/2 if that makes sense
